// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sample_crm.Data;

#nullable disable

namespace sample_crm.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sample_crm.Core.Entities.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FlowSateId")
                        .HasColumnType("int");

                    b.Property<int?>("FlowStateId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlowStateId");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("sample_crm.Core.Entities.FlowState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FlowStates");
                });

            modelBuilder.Entity("sample_crm.Core.Entities.Flow", b =>
                {
                    b.HasOne("sample_crm.Core.Entities.FlowState", "FlowState")
                        .WithMany("Flows")
                        .HasForeignKey("FlowStateId");

                    b.Navigation("FlowState");
                });

            modelBuilder.Entity("sample_crm.Core.Entities.FlowState", b =>
                {
                    b.Navigation("Flows");
                });
#pragma warning restore 612, 618
        }
    }
}
